name: NULL@ROOT
bio: Underground hacker group
description: Yes, we do something! 🙂
external-image: false
picture: assets/images/NR-Origami3-300x300-black.png
#resume: true
#resume-external: true
#resume-url: 'https://google.com/?q=my+resume'
url: 'https://null2root.github.io' #'https://koppl.in/indigo'
#permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - about
    - history
    - members
    - blog
    - project
#facebook: myfacebook
#twitter: mytwitter
github: null2root
#medium: medium
email: admin@null2root.org
authors:
  null2root:
    name: null2root
    bio: underground hacker group
    external-image: false
    #picture: assets/images/profile.jpg
    picture: assets/images/NR-Origami3-300x300-black.png
    #twitter: johndoe
  cheese:
    name: cheese
    bio: I don't really like cheese actually. 
    external-image: false
    picture: assets/images/cheese.jpg
    #twitter: jamesfoster
  kerz:
    name: kerz
    bio: Cyber security engineer at this life.
    external-image: false
    picture: assets/images/kerz.png
    #twitter: jamesfoster
width: normal
members: true
projects: false
about: true
history: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
  
tag_archive:
  type: liquid
  path: /tags/
